name: auto-deploy-to-server

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    name: Building project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_PROD }}

  update_server:
    name: Updating production project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: update current container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME_OR_IPADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PROD_PROJECT_FOLDER }};
            docker compose -f docker-compose.yml pull;
            docker compose -f docker-compose.yml down;
            docker compose -f docker-compose.yml up -d;